from typing import Protocol

class AuthServiceProtocol(Protocol):
    async def register(self): ...

    async def login(self, identifier: str, password: str): ...

    async def refresh(self, refresh_token: str): ...

    async def logout(self, refresh_token: str | None = None): ...
