from typing import Protocol
from uuid import UUID

from src.models import User


class UserServiceProtocol(Protocol):
    async def get_user_by_id(self, user_id: UUID) -> User: ...
    async def get_user_by_email(self, email: str) -> User: ...
    async def check_email_exists(self, email: str) -> bool: ...
    async def check_username_exists(self, username: str) -> bool: ...
    async def add_new_user(self, new_user: User) -> User: ...

    # TODO return type hint
    async def get_profile(self, user_id: UUID): ...

