"""add user_profiles table and extend short_url_visits

Revision ID: 541e53335ee7
Revises: 937bd6f2c32b
Create Date: 2026-04-14 23:17:58.461283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '541e53335ee7'
down_revision: Union[str, Sequence[str], None] = '937bd6f2c32b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('emoji_avatar', sa.String(length=50), nullable=False),
    sa.Column('ui_theme', sa.String(length=10), nullable=False),
    sa.Column('ui_language', sa.String(length=2), nullable=False),
    sa.Column('bio', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.add_column('short_url_visits', sa.Column('ip_hash', sa.String(length=255), nullable=False))
    op.add_column('short_url_visits', sa.Column('city', sa.String(length=255), nullable=True))
    op.add_column('short_url_visits', sa.Column('os', sa.String(length=255), nullable=True))
    op.add_column('short_url_visits', sa.Column('browser', sa.String(length=255), nullable=True))
    op.add_column('short_url_visits', sa.Column('referrer', sa.String(length=255), nullable=True))
    op.add_column('short_url_visits', sa.Column('referrer_domain', sa.String(length=255), nullable=True))
    op.add_column('short_url_visits', sa.Column('is_unique', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('telegram_id', sa.BigInteger(), nullable=True))
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'telegram_id')
    op.drop_column('short_url_visits', 'is_unique')
    op.drop_column('short_url_visits', 'referrer_domain')
    op.drop_column('short_url_visits', 'referrer')
    op.drop_column('short_url_visits', 'browser')
    op.drop_column('short_url_visits', 'os')
    op.drop_column('short_url_visits', 'city')
    op.drop_column('short_url_visits', 'ip_hash')
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
