"""increase ShortUrl.short_url max length from 6 to 30

Revision ID: 6d3b2f9b4887
Revises: a6e3d894374a
Create Date: 2026-04-08 17:25:25.148030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d3b2f9b4887'
down_revision: Union[str, Sequence[str], None] = 'a6e3d894374a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('short_urls', 'short_url',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.String(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('short_urls', 'short_url',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)
    # ### end Alembic commands ###
