"""Add users, short_url_visits tables, update short_urls (add FK_users)

Revision ID: 937bd6f2c32b
Revises: 6d3b2f9b4887
Create Date: 2026-04-09 20:58:22.793711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '937bd6f2c32b'
down_revision: Union[str, Sequence[str], None] = '6d3b2f9b4887'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('short_url_visits',
    sa.Column('short_url_id', sa.Uuid(), nullable=False),
    sa.Column('visited_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('device_type', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['short_url_id'], ['short_urls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Add as nullable first to allow backfilling existing rows.
    op.add_column('short_urls', sa.Column('slug', sa.String(length=30), nullable=True))
    op.execute("UPDATE short_urls SET slug = short_url")
    op.alter_column(
        'short_urls',
        'slug',
        existing_type=sa.String(length=30),
        nullable=False,
    )
    op.add_column('short_urls', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.drop_index(op.f('ix_short_urls_short_url'), table_name='short_urls')
    op.create_index(op.f('ix_short_urls_slug'), 'short_urls', ['slug'], unique=True)
    op.create_foreign_key(None, 'short_urls', 'users', ['user_id'], ['id'])
    op.drop_column('short_urls', 'short_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Reverse: add old column as nullable, backfill from slug, then set NOT NULL.
    op.add_column(
        'short_urls',
        sa.Column('short_url', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    )
    op.execute("UPDATE short_urls SET short_url = slug")
    op.alter_column(
        'short_urls',
        'short_url',
        existing_type=sa.VARCHAR(length=30),
        nullable=False,
    )
    # noinspection PyTypeChecker
    op.drop_constraint(None, 'short_urls', type_='foreignkey')
    op.drop_index(op.f('ix_short_urls_slug'), table_name='short_urls')
    op.create_index(op.f('ix_short_urls_short_url'), 'short_urls', ['short_url'], unique=True)
    op.drop_column('short_urls', 'user_id')
    op.drop_column('short_urls', 'slug')
    op.drop_table('short_url_visits')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
